// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-L/app/model/internal"
)

// ProvinceCityCode is the golang structure for table province_city_code.
type ProvinceCityCode internal.ProvinceCityCode

// Fill with you ideas below.
type IdCardApiReq struct {
	Code string `v:"required#请输入代码"`
}
