# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-L"
	LogPath     = "/tmp/log/gf-L/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-L"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:1234@tcp(127.0.0.1:3306)/L"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-L/sql"
        Level  = "all"
        Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        link   = "mysql:root:1234@tcp(127.0.0.1:3306)/l"
        tables = "user"