// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-L/app/dao/internal"
)

// provinceCityCodeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type provinceCityCodeDao struct {
	internal.ProvinceCityCodeDao
}

var (
	// ProvinceCityCode is globally public accessible object for table province_city_code operations.
	ProvinceCityCode = provinceCityCodeDao{
		internal.ProvinceCityCode,
	}
)

// Fill with you ideas below.
